# Generated by Django 2.1.7 on 2019-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
